// flow-typed signature: 7e18cb289dd5a0be37ec39a82e496d1d
// flow-typed version: <<STUB>>/env-paths_v^1.0.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'env-paths'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'env-paths' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'env-paths/index' {
  declare module.exports: $Exports<'env-paths'>;
}
declare module 'env-paths/index.js' {
  declare module.exports: $Exports<'env-paths'>;
}
