// flow-typed signature: a1acecc37f4547a46f9f655a30c6cf3f
// flow-typed version: <<STUB>>/sodium-native_v^2.1.5/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sodium-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sodium-native' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sodium-native/example' {
  declare module.exports: any;
}

declare module 'sodium-native/postinstall' {
  declare module.exports: any;
}

declare module 'sodium-native/preinstall' {
  declare module.exports: any;
}

declare module 'sodium-native/test/crypto_auth' {
  declare module.exports: any;
}

declare module 'sodium-native/test/crypto_box' {
  declare module.exports: any;
}

declare module 'sodium-native/test/crypto_generichash' {
  declare module.exports: any;
}

declare module 'sodium-native/test/crypto_hash_sha256' {
  declare module.exports: any;
}

declare module 'sodium-native/test/crypto_hash_sha512' {
  declare module.exports: any;
}

declare module 'sodium-native/test/crypto_hash' {
  declare module.exports: any;
}

declare module 'sodium-native/test/crypto_kdf' {
  declare module.exports: any;
}

declare module 'sodium-native/test/crypto_kx' {
  declare module.exports: any;
}

declare module 'sodium-native/test/crypto_onetimeauth' {
  declare module.exports: any;
}

declare module 'sodium-native/test/crypto_pwhash' {
  declare module.exports: any;
}

declare module 'sodium-native/test/crypto_scalarmult' {
  declare module.exports: any;
}

declare module 'sodium-native/test/crypto_secretbox' {
  declare module.exports: any;
}

declare module 'sodium-native/test/crypto_secretstream' {
  declare module.exports: any;
}

declare module 'sodium-native/test/crypto_shorthash' {
  declare module.exports: any;
}

declare module 'sodium-native/test/crypto_sign' {
  declare module.exports: any;
}

declare module 'sodium-native/test/crypto_stream' {
  declare module.exports: any;
}

declare module 'sodium-native/test/fixtures/mprotect_noaccess' {
  declare module.exports: any;
}

declare module 'sodium-native/test/fixtures/mprotect_readonly' {
  declare module.exports: any;
}

declare module 'sodium-native/test/fixtures/mprotect_readwrite' {
  declare module.exports: any;
}

declare module 'sodium-native/test/memory' {
  declare module.exports: any;
}

declare module 'sodium-native/test/padding' {
  declare module.exports: any;
}

declare module 'sodium-native/test/randombytes' {
  declare module.exports: any;
}

declare module 'sodium-native/test/sodium-test' {
  declare module.exports: any;
}

declare module 'sodium-native/test/vectors' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sodium-native/example.js' {
  declare module.exports: $Exports<'sodium-native/example'>;
}
declare module 'sodium-native/index' {
  declare module.exports: $Exports<'sodium-native'>;
}
declare module 'sodium-native/index.js' {
  declare module.exports: $Exports<'sodium-native'>;
}
declare module 'sodium-native/postinstall.js' {
  declare module.exports: $Exports<'sodium-native/postinstall'>;
}
declare module 'sodium-native/preinstall.js' {
  declare module.exports: $Exports<'sodium-native/preinstall'>;
}
declare module 'sodium-native/test/crypto_auth.js' {
  declare module.exports: $Exports<'sodium-native/test/crypto_auth'>;
}
declare module 'sodium-native/test/crypto_box.js' {
  declare module.exports: $Exports<'sodium-native/test/crypto_box'>;
}
declare module 'sodium-native/test/crypto_generichash.js' {
  declare module.exports: $Exports<'sodium-native/test/crypto_generichash'>;
}
declare module 'sodium-native/test/crypto_hash_sha256.js' {
  declare module.exports: $Exports<'sodium-native/test/crypto_hash_sha256'>;
}
declare module 'sodium-native/test/crypto_hash_sha512.js' {
  declare module.exports: $Exports<'sodium-native/test/crypto_hash_sha512'>;
}
declare module 'sodium-native/test/crypto_hash.js' {
  declare module.exports: $Exports<'sodium-native/test/crypto_hash'>;
}
declare module 'sodium-native/test/crypto_kdf.js' {
  declare module.exports: $Exports<'sodium-native/test/crypto_kdf'>;
}
declare module 'sodium-native/test/crypto_kx.js' {
  declare module.exports: $Exports<'sodium-native/test/crypto_kx'>;
}
declare module 'sodium-native/test/crypto_onetimeauth.js' {
  declare module.exports: $Exports<'sodium-native/test/crypto_onetimeauth'>;
}
declare module 'sodium-native/test/crypto_pwhash.js' {
  declare module.exports: $Exports<'sodium-native/test/crypto_pwhash'>;
}
declare module 'sodium-native/test/crypto_scalarmult.js' {
  declare module.exports: $Exports<'sodium-native/test/crypto_scalarmult'>;
}
declare module 'sodium-native/test/crypto_secretbox.js' {
  declare module.exports: $Exports<'sodium-native/test/crypto_secretbox'>;
}
declare module 'sodium-native/test/crypto_secretstream.js' {
  declare module.exports: $Exports<'sodium-native/test/crypto_secretstream'>;
}
declare module 'sodium-native/test/crypto_shorthash.js' {
  declare module.exports: $Exports<'sodium-native/test/crypto_shorthash'>;
}
declare module 'sodium-native/test/crypto_sign.js' {
  declare module.exports: $Exports<'sodium-native/test/crypto_sign'>;
}
declare module 'sodium-native/test/crypto_stream.js' {
  declare module.exports: $Exports<'sodium-native/test/crypto_stream'>;
}
declare module 'sodium-native/test/fixtures/mprotect_noaccess.js' {
  declare module.exports: $Exports<'sodium-native/test/fixtures/mprotect_noaccess'>;
}
declare module 'sodium-native/test/fixtures/mprotect_readonly.js' {
  declare module.exports: $Exports<'sodium-native/test/fixtures/mprotect_readonly'>;
}
declare module 'sodium-native/test/fixtures/mprotect_readwrite.js' {
  declare module.exports: $Exports<'sodium-native/test/fixtures/mprotect_readwrite'>;
}
declare module 'sodium-native/test/memory.js' {
  declare module.exports: $Exports<'sodium-native/test/memory'>;
}
declare module 'sodium-native/test/padding.js' {
  declare module.exports: $Exports<'sodium-native/test/padding'>;
}
declare module 'sodium-native/test/randombytes.js' {
  declare module.exports: $Exports<'sodium-native/test/randombytes'>;
}
declare module 'sodium-native/test/sodium-test.js' {
  declare module.exports: $Exports<'sodium-native/test/sodium-test'>;
}
declare module 'sodium-native/test/vectors.js' {
  declare module.exports: $Exports<'sodium-native/test/vectors'>;
}
